import './globals.css'
import type { Metadata } from 'next'
import SiteHeader from '@/components/SiteHeader'
import { Satoshi } from '@/utils/fonts'
import SiteFooter from '@/components/SiteFooter'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
//! This is the metadata for the site, it is used by the SEO component, remember to change it to your own data and remove this comment jaja

// export const metadata: Metadata = {
//   metadataBase: new URL(
//     process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000',
//   ),
//   title: {
//     default: siteConfig.name,
//     template: `%s - ${siteConfig.name}`,
//   },
//   description: siteConfig.description,
//   keywords: [
//     'Next.js',
//     'React',
//     'Tailwind CSS',
//     'TypeScript',
//     'Shadcn',
//     'Pamsho',
//     'Portfolio',
//     'Blog',
//     'Web Development',
//     'Frontend Development',
//     'Fullstack Development',
//     'Sanity',
//   ],
//   authors: [
//     {
//       name: 'Pamsho',
//       url: 'https://github.com/JorgeAssaf',
//     },
//   ],
//   creator: 'Pamsho',
//   themeColor: [
//     { media: '(prefers-color-scheme: light)', color: 'white' },
//     { media: '(prefers-color-scheme: dark)', color: 'black' },
//   ],
//   openGraph: {
//     type: 'website',
//     locale: 'en_US',
//     url: siteConfig.url,
//     title: siteConfig.name,
//     description: siteConfig.description,
//     siteName: siteConfig.name,
//   },
//   twitter: {
//     card: 'summary_large_image',
//     title: siteConfig.name,
//     description: siteConfig.description,
//     images: [`${siteConfig.url}/opengraph-image.png`],
//     creator: '@AssafEnrique',
//   },
//   icons: {
//     icon: '/favicon.ico',
//   },
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={cn(
          Satoshi.className,
          'items-center flex flex-col sticky',
        )}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <main className='w-full sm:w-9/12   sticky flex flex-col  h-screen '>
            <SiteHeader />
            <div className='w-full flex flex-col flex-1  gap-3 h-auto px-8'>
              {children}
            </div>
            <SiteFooter />
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
