import "./globals.css";
import type { Metadata } from "next";
import SiteHeader from "@/components/SiteHeader";
import { Satoshi } from "@/utils/fonts";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={Satoshi.className + "  items-center flex flex-col  sticky"}
      >
        <main className="w-full sm:w-9/12   sticky flex flex-col  h-screen ">
          <SiteHeader />
          <div className="w-full flex flex-col flex-1  gap-3 h-auto px-8">
            {children}
          </div>
          <SiteFooter />
        </main>
      </body>
    </html>
  );
}
